version : '2'

services:
  nginx:
    image: nginx:latest
    container_name: todo_app_nginx
    ports:
      - '8080:80'
    volumes_from:
      - todo_app_api:ro
    volumes:
      - ./docker/nginx/conf.d/todo_app_api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - todo_app_api
    
  todo_app_pg:
    image: postgres:latest
    container_name: todo_app_pg
    hostname: todo_app_pg
    restart: always
    env_file: './docker/environments'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=todoapppass
      - POSTGRES_USER=todoapp
      - POSTGRES_DB=todoapp
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - ./todo_app_pg_data:/var/lib/postgresql/9.7/main
  
  todo_app_api:
    build: ./
    container_name: todo_app_api
    hostname: todo_app_api
    restart: always
    volumes:
      - ./todo:/DjangoToDo/todo
      - ./todo_api:/DjangoToDo/todo_api
      - ./static:/DjangoToDo/static
    env_file: './docker/environments'
    ports:
      - '8000:8000'
  
  todo_app_client:
    image: node:latest
    container_name: todo_app_client
    hostname: todo_app_client
    volumes:
      - .:/DjangoToDo
    command: "/bin/bash -c 'cd /DjangoToDo && npm install && npm start'"
    ports:
     - '3000:3000'
    network_mode: 'host'
    expose:
     - '3000'

volumes:
  todo_app_pg_data:
